server:
  port: 8086
  servlet:
    context-path: /
  
spring:
  main:
    banner-mode: "off"
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/psnpbind?requireSSL=false&useSSL=false
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
    cache: false
  
logging:
  level:
    org:
      springframework: ERROR
